### ISSUE TITLE
Error running plug-in

### ISSUE THREAD

**Issue by jameswestcott** [neilpatel121/homebridge-skyq-tvremote#17]
HomeBridge won't start and shows following error with this plug-in:

TypeError: Cannot read property 'Characteristic' of undefined
    at SkyTVPlugin.publishExternalAccessory (C:\Users\james\AppData\Roaming\npm\node_modules\homebridge-skyq-tvremote\src\platform.ts:99:48)
    at C:\Users\james\AppData\Roaming\npm\node_modules\homebridge-skyq-tvremote\src\platform.ts:48:14
    at Array.forEach (<anonymous>)
    at new SkyTVPlugin (C:\Users\james\AppData\Roaming\npm\node_modules\homebridge-skyq-tvremote\src\platform.ts:45:22)
    at C:\Users\james\AppData\Roaming\npm\node_modules\homebridge\src\server.ts:377:40
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (C:\Users\james\AppData\Roaming\npm\node_modules\homebridge\src\server.ts:312:27)
    at Server.start (C:\Users\james\AppData\Roaming\npm\node_modules\homebridge\src\server.ts:116:29)

**Comment by EpicKris** [comment]
You must use the issue template below when submitting a bug

**Describe The Bug:**


**To Reproduce:**


**Expected behavior:**


**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**


**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by EpicKris** [comment]
Please try the latest release.
