### ISSUE TITLE
Unhandled exception in log at every startup for Sky Q Platinum + 3 Mini for Sky Italy

### ISSUE THREAD

**Issue by luigi-lauro** [neilpatel121/homebridge-skyq-tvremote#23]
**Describe The Bug:**
Unhandled exception in the log at every startup of Homebridge or plugin. It seems to be something related to duplicated channels or something. I run a setup with a Sky Q Platinum and 3x Sky Q Mini for Sky Italia (Italy).

**To Reproduce:**
Just restart Homebridge or restart child bridge for plugin.

**Expected behavior:**
No exception

**Logs:**
[5/3/2021, 4:04:27 PM] [homebridge-skyq-tvremote] Restarting Process...
Initializing HAP-NodeJS v0.9.4...
[5/3/2021, 4:04:28 PM] [homebridge-skyq-tvremote] Launched child bridge with PID 2628
[5/3/2021, 4:04:28 PM] Registering platform 'homebridge-skyq-tvremote.skyq-tvremote'
[5/3/2021, 4:04:28 PM] [homebridge-skyq-tvremote] Loaded homebridge-skyq-tvremote v1.3.0 child bridge successfully
[5/3/2021, 4:04:28 PM] Loaded 0 cached accessories from cachedAccessories.0E83B399104C.
[5/3/2021, 4:04:28 PM] [homebridge-skyq-tvremote] Sky TV platform finished initializing!
Preparing Advertiser for 'homebridge-skyq-tvremote C934' using bonjour-hap backend!
Starting to advertise 'homebridge-skyq-tvremote C934' using bonjour-hap backend!
[5/3/2021, 4:04:28 PM] Homebridge v1.3.4 (homebridge-skyq-tvremote) is running on port 56339.
Preparing Advertiser for 'Sky Q Platinum Sala CC60' using bonjour-hap backend!
Preparing Advertiser for 'Sky Q Mini Cucina E964' using bonjour-hap backend!
Preparing Advertiser for 'Sky Q Mini Camera EE51' using bonjour-hap backend!
Preparing Advertiser for 'Sky Q Mini Cameretta 3326' using bonjour-hap backend!
Starting to advertise 'Sky Q Platinum Sala CC60' using bonjour-hap backend!
[5/3/2021, 4:04:28 PM] Sky Q Platinum Sala CC60 is running on port 38307.
[5/3/2021, 4:04:28 PM] Please add [Sky Q Platinum Sala CC60] manually in Home app. Setup Code: REMOVED
Starting to advertise 'Sky Q Mini Cucina E964' using bonjour-hap backend!
[5/3/2021, 4:04:28 PM] Sky Q Mini Cucina E964 is running on port 38199.
[5/3/2021, 4:04:28 PM] Please add [Sky Q Mini Cucina E964] manually in Home app. Setup Code: REMOVED
Starting to advertise 'Sky Q Mini Camera EE51' using bonjour-hap backend!
[5/3/2021, 4:04:28 PM] Sky Q Mini Camera EE51 is running on port 45345.
[5/3/2021, 4:04:28 PM] Please add [Sky Q Mini Camera EE51] manually in Home app. Setup Code: REMOVED
Starting to advertise 'Sky Q Mini Cameretta 3326' using bonjour-hap backend!
[5/3/2021, 4:04:28 PM] Sky Q Mini Cameretta 3326 is running on port 36165.
[5/3/2021, 4:04:28 PM] Please add [Sky Q Mini Cameretta 3326] manually in Home app. Setup Code: REMOVED
(node:2628) UnhandledPromiseRejectionWarning: Error: Cannot add a Service with the same UUID '000000D9-0000-1000-8000-0026BB765291' and subtype 'Sky Sport Serie A HD' as another Service in this Accessory.
    at Accessory.addService (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:448:17)
    at PlatformAccessory.addService (/usr/lib/node_modules/homebridge/src/platformAccessory.ts:93:41)
    at /usr/lib/node_modules/homebridge-skyq-tvremote/src/platform.ts:152:42
    at Array.forEach (<anonymous>)
    at /usr/lib/node_modules/homebridge-skyq-tvremote/src/platform.ts:147:23
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:2628) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2628) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:2628) UnhandledPromiseRejectionWarning: Error: Cannot add a Service with the same UUID '000000D9-0000-1000-8000-0026BB765291' and subtype 'Sky Sport Serie A HD' as another Service in this Accessory.
    at Accessory.addService (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:448:17)
    at PlatformAccessory.addService (/usr/lib/node_modules/homebridge/src/platformAccessory.ts:93:41)
    at /usr/lib/node_modules/homebridge-skyq-tvremote/src/platform.ts:152:42
    at Array.forEach (<anonymous>)
    at /usr/lib/node_modules/homebridge-skyq-tvremote/src/platform.ts:147:23
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:2628) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:2628) UnhandledPromiseRejectionWarning: Error: Cannot add a Service with the same UUID '000000D9-0000-1000-8000-0026BB765291' and subtype 'Sky Sport Serie A HD' as another Service in this Accessory.
    at Accessory.addService (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:448:17)
    at PlatformAccessory.addService (/usr/lib/node_modules/homebridge/src/platformAccessory.ts:93:41)
    at /usr/lib/node_modules/homebridge-skyq-tvremote/src/platform.ts:152:42
    at Array.forEach (<anonymous>)
    at /usr/lib/node_modules/homebridge-skyq-tvremote/src/platform.ts:147:23
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:2628) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:2628) UnhandledPromiseRejectionWarning: Error: Cannot add a Service with the same UUID '000000D9-0000-1000-8000-0026BB765291' and subtype 'Sky Sport Serie A HD' as another Service in this Accessory.
    at Accessory.addService (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:448:17)
    at PlatformAccessory.addService (/usr/lib/node_modules/homebridge/src/platformAccessory.ts:93:41)
    at /usr/lib/node_modules/homebridge-skyq-tvremote/src/platform.ts:152:42
    at Array.forEach (<anonymous>)
    at /usr/lib/node_modules/homebridge-skyq-tvremote/src/platform.ts:147:23
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:2628) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
[5/3/2021, 4:04:30 PM] [homebridge-skyq-tvremote] [Sky Q Mini Camera] Get Active: INACTIVE
[5/3/2021, 4:04:30 PM] [homebridge-skyq-tvremote] [Sky Q Platinum Sala] Get Active: INACTIVE
[5/3/2021, 4:04:31 PM] [homebridge-skyq-tvremote] [Sky Q Mini Cucina] Get Active: ACTIVE
[5/3/2021, 4:04:31 PM] [homebridge-skyq-tvremote] [Sky Q Mini Cameretta] Get Active: INACTIVE
[5/3/2021, 4:04:37 PM] [homebridge-skyq-tvremote] [Sky Q Mini Camera] Get Active: INACTIVE
[5/3/2021, 4:04:48 PM] [homebridge-skyq-tvremote] [Sky Q Platinum Sala] Get Active: INACTIVE
[5/3/2021, 4:04:48 PM] [homebridge-skyq-tvremote] [Sky Q Mini Camera] Get Active: INACTIVE
[5/3/2021, 4:04:48 PM] [homebridge-skyq-tvremote] [Sky Q Mini Cameretta] Get Active: INACTIVE

**Plugin Config:**
{
    "bridge": {
        "name": "Homebridge REMOVED",
        "username": REMOVED,
        "port": REMOVED,
        "pin": REMOVED,
        "bind": [
            "eth0"
        ]
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "none",
            "theme": "auto",
            "tempUnits": "c",
            "lang": "auto",
            "platform": "config"
        },
        {
            "devices": [
                {
                    "name": "Sky Q Platinum Sala",
                    "ipAddress": "192.168.4.73"
                },
                {
                    "name": "Sky Q Mini Cucina",
                    "ipAddress": "192.168.4.86"
                },
                {
                    "name": "Sky Q Mini Camera",
                    "ipAddress": "192.168.4.88"
                },
                {
                    "name": "Sky Q Mini Cameretta",
                    "ipAddress": "192.168.4.124"
                }
            ],
            "_bridge": {
                "username": "0E:83:B3:99:10:4C",
                "port": 56339
            },
            "platform": "skyq-tvremote"
        }
    ],
    "disabledPlugins": []
}

**Environment:**

* **Plugin Version**: homebridge-skyq-tvremote v1.3.0
* **Homebridge Version**: 1.3.4
* **Node.js Version**: v12.20.0
* **NPM Version**: 6.14.8
* **Operating System**: Raspbian

**Comment by luigi-lauro** [comment]
Updated with correct bug template.

**Comment by EpicKris** [comment]
Could you test `v1.3.0-beta.0`?

**Comment by luigi-lauro** [comment]
I will try later, I need to see how to install a beta version, usually I use config UI for plugins install/update, need to see how to do it from rpi command line but I'll try and get back

**Comment by EpicKris** [comment]
> I will try later, I need to see how to install a beta version, usually I use config UI for plugins install/update, need to see how to do it from rpi command line but I'll try and get back

You can install beta versions using the Config UI.

Go to the Plugins tab, select the tool (right of Settings), select Install Previous Version, select the latest beta, then select select Install.

You'll need to revert to the latest version manually after testing.

**Comment by luigi-lauro** [comment]
I confirm, fixed in beta1. Thank you.

**Comment by luigi-lauro** [comment]
Just as a note: now only favorite channels are added, which I think it's better and makes sense.
