### ISSUE TITLE
Homebridge will not start

### ISSUE THREAD

**Issue by Crox77** [neilpatel121/homebridge-skyq-tvremote#26]
**Describe The Bug:**
Homebridge will not start keep getting the below error message. ip dress is configured in settings ok and at the Sky box itself and in my router settings

**To Reproduce:**

**Expected behavior:**

**Logs:**

```
Error: Cannot add more than 100 services to a single accessory!
    at Accessory.addService (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:453:13)
    at PlatformAccessory.addService (/usr/local/lib/node_modules/homebridge/src/platformAccessory.ts:93:41)
    at /usr/local/lib/node_modules/homebridge-skyq-tvremote/src/platform.ts:152:42
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/homebridge-skyq-tvremote/src/platform.ts:147:23
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Cannot add more than 100 services to a single accessory!
    at Accessory.addService (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:453:13)
    at PlatformAccessory.addService (/usr/local/lib/node_modules/homebridge/src/platformAccessory.ts:93:41)
    at /usr/local/lib/node_modules/homebridge-skyq-tvremote/src/platform.ts:152:42
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/homebridge-skyq-tvremote/src/platform.ts:147:23
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Plugin Config:**

```json
{
			"name": "Sky Q TV Remote",
			"platform": "skyq-tvremote",
			"devices": [{
				"name": "Sky Q TV",
				"ipaddress": "192.168.1.5"
			}]
		},
```

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by EpicKris** [comment]
Could you test `v1.3.0-beta.1`?
