### ISSUE TITLE
Sky Q Mini BUG

### ISSUE THREAD

**Issue by MrNoooooooob** [neilpatel121/homebridge-skyq-tvremote#30]
**Describe The Bug:**
If you add the Sky Q Mini then you have to restart the Homebridge and I did that and then the errors appear, but when you add the Sky Q Reciver, the error is not only there with the Sky Q Mini and me I don't get the bug fixed either because it seems to be a bug.

After removing the Sky Q Mini from the device, everything works again, but as soon as I add it again, the error is there again even after restarting several times or after reinstalling the plugin, the error is still there. 

**To Reproduce:**
?

**Expected behavior:**
Working

**Logs:**

```
Loading logs using native method...
File: /homebridge/homebridge.log

1m    url: 'http://192.168.178.29:9006/as/system/information',
    json: true,
    callback: [Function: RP$callback],
    transform: undefined,
    simple: true,
    resolveWithFullResponse: false,
    transform2xxOnly: false
  },
  response: undefined
}
[6/3/2021, 8:56:21 PM] [skyq-tvremote] RequestError: Error: connect ECONNREFUSED 192.168.178.29:9006
    at new RequestError (/homebridge/node_modules/homebridge-skyq-tvremote/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/homebridge/node_modules/homebridge-skyq-tvremote/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/homebridge/node_modules/homebridge-skyq-tvremote/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/homebridge/node_modules/homebridge-skyq-tvremote/node_modules/request/request.js:185:22)
    at Request.emit (events.js:376:20)
    at Request.onRequestError (/homebridge/node_modules/homebridge-skyq-tvremote/node_modules/request/request.js:877:8)
    at ClientRequest.emit (events.js:376:20)
    at Socket.socketErrorListener (_http_client.js:475:9)
    at Socket.emit (events.js:376:20)
    at emitErrorNT (internal/streams/destroy.js:106:8) {
  cause: Error: connect ECONNREFUSED 192.168.178.29:9006
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '192.168.178.29',
    port: 9006
  },
  error: Error: connect ECONNREFUSED 192.168.178.29:9006
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '192.168.178.29',
    port: 9006
  },
  options: {
    url: 'http://192.168.178.29:9006/as/system/information',
    json: true,
    callback: [Function: RP$callback],
    transform: undefined,
    simple: true,
    resolveWithFullResponse: false,
    transform2xxOnly: false
  },
  response: undefined
}
```

**Plugin Config:**

```json
{
    "bridge": {
        "name": "Homebridge",
        "username": "SN",
        "port": SN,
        "pin": "SN"
    },
    "description": "Home Smart Home",
    "platforms": [
        {
            "name": "Config",
            "port": 8080,
            "auth": "form",
            "theme": "dark-mode",
            "temp": "/sys/class/thermal/thermal_zone0/temp",
            "tempUnits": "c",
            "lang": "de",
            "platform": "config"
        },
        {
            "name": "SamsungTizen",
            "devices": [
                {
                    "name": "Wohnzimmer Fernseher",
                    "ip": "192.168.178.36",
                    "mac": "SN",
                    "inputs": [
                        {
                            "name": "Sky Q",
                            "type": "command"
                        },
                        {
                            "name": "Xbox One X",
                            "type": "command"
                        },
                        {
                            "name": "Nintendo Switch",
                            "type": "command"
                        },
                        {
                            "name": "Netflix",
                            "type": "app",
                            "value": "11101200001"
                        },
                        {
                            "name": "Apple Music",
                            "type": "app",
                            "value": "201908019041"
                        },
                        {
                            "name": "Apple TV",
                            "type": "app",
                            "value": "3201807016597"
                        },
                        {
                            "name": "Disney+",
                            "type": "app",
                            "value": "3201901017640"
                        }
                    ]
                },
                {
                    "name": "Schlafzimmer Fernseher",
                    "ip": "192.168.178.30",
                    "mac": "SN",
                    "inputs": [
                        {
                            "name": "Apple Tivi",
                            "type": "command"
                        },
                        {
                            "name": "Netflix",
                            "type": "app",
                            "value": "11101200001"
                        },
                        {
                            "name": "Apple Music",
                            "type": "app",
                            "value": "201908019041"
                        },
                        {
                            "name": "Apple TV",
                            "type": "app",
                            "value": "3201807016597"
                        },
                        {
                            "name": "Disney+",
                            "type": "app",
                            "value": "3201901017640"
                        }
                    ]
                }
            ],
            "platform": "SamsungTizen"
        },
        {
            "devices": [
                {
                    "name": "Xbox One X",
                    "host": "192.168.178.46",
                    "xboxliveid": "SN",
                    "refreshInterval": 5,
                    "disableLogInfo": true,
                    "volumeControl": 0,
                    "switchInfoMenu": true,
                    "inputs": [
                        {
                            "name": "Spotify",
                            "reference": "SpotifyAB.SpotifyMusic-forXbox_zpdnekdrzrea0!App",
                            "type": "APPLICATION"
                        }
                    ],
                    "manufacturer": "Microsoft Corporation"
                }
            ],
            "platform": "XboxTv"
        },
        {
            "devices": [
                {
                    "name": "Sky Q",
                    "ipAddress": "192.168.178.22"
                }
                {
                    "name": "Sky Q Mini",
                    "ipAddress": "192.168.178.29"
                }            
          ],
            "platform": "skyq-tvremote"
        }
    ],
    "accessories": [
        {
            "accessory": "RaspberryPiTemperature",
            "name": "RaspberryPi CPU Temperature",
            "updateInterval": 1000
        }
    ]
}
```

**Screenshots:**
<img width="1399" alt="Bildschirmfoto 2021-06-03 um 20 57 50" src="https://user-images.githubusercontent.com/70014906/120717305-9ad33100-c4c7-11eb-8bd0-43eafcbc65d8.png">

**Environment:**

* **Plugin Version**: v1.4.0
* **Homebridge Version**: v1.3.4
* **Node.js Version**: v14.17.0
* **NPM Version**: v7.15.0
* **Operating System**: Raspberry Pi -> Docker

**Comment by EpicKris** [comment]
Are you sure that the IP address is correct?

Could you try to visit http://192.168.178.29:9006/as/system/information from a browser on your local network and see if that shows anything?

**Comment by MrNoooooooob** [comment]
The IP is correct and I have now also tested via LAN and the error is still there and Sky Q Mini cannot be controlled. 

When I go to the link, nothing opens up, i.e. no information about the device

**Comment by EpicKris** [comment]
So I've just tested this with another Sky Q Mini and regardless of whether the Sky Q is a regular or mini box, the URL should load from a browser. If it doesn't there's a communication error on your local network with the Sky Q box. I would recommend restarting your network and the Sky Q Mini and verifying the IP address.

**Comment by MrNoooooooob** [comment]
The reciver is also highlighted in gray in the FRITZ! Box, I have now implemented the tip you suggested and nothing happens and it is still highlighted in gray and I'm afraid that the Sky Q Mini will not release the port,
I have already reset and set up again, I also activated port sharing, but nothing happens either.
It can't be because of the router because I've never been able to access the Sky Q Mini

Thank you in advance for the help.


<img width="323" alt="Bildschirmfoto 2021-06-06 um 20 17 07" src="https://user-images.githubusercontent.com/70014906/120935709-4799f200-c704-11eb-833a-b37889867b7c.png">

**Comment by EpicKris** [comment]
This doesn't show the IP address. Where are you getting the IP address from?

**Comment by MrNoooooooob** [comment]
The device is currently defective, so it may not be displayed in blue in the FRITZ! Box 6660 Cable.

I am waiting for an answer from Sky as they have to send me a new device.


With the FRITZ! Box, blue means that there is a link in the device where it can be accessed via the website.

Sorry for the late reply.
But I will report back whether it worked with the new box.

**Comment by EpicKris** [comment]
Could you test `v1.4.0-beta.2` to check it doesn't crash Homebridge entirely and notifies you of an incorrect IP address?

**Comment by MrNoooooooob** [comment]
The IP is correct but the error is still displayed with the version 1.4.0 beta 2, I have already deleted from the cache and the plugin also reinstalled and it is not feasible ..
The same mistakes as above.

**Comment by MrNoooooooob** [comment]
???

**Comment by EpicKris** [comment]
Did you remove the accessory from HomeKit and re-add it?

**Comment by MrNoooooooob** [comment]
I have inserted the log here.

I uninstalled the plugin and reinstalled again as well as removed from the homekit (SKY Q Mini can not be added) So I do not remember.

<img width="957" alt="Bildschirmfoto 2021-07-23 um 23 33 12" src="https://user-images.githubusercontent.com/70014906/126843774-06bf1b10-99ff-44ab-b0ae-3125f3cfc452.png">

```
[7/23/2021, 11:26:10 PM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[7/23/2021, 11:26:15 PM] [HB Supervisor] Restarting Homebridge...
[7/23/2021, 11:26:15 PM] [HB Supervisor] Starting Homebridge with extra flags: -I -D -K
[7/23/2021, 11:26:15 PM] [HB Supervisor] Started Homebridge v1.3.4 with PID: 29248
Initializing HAP-NodeJS v0.9.4...
[7/23/2021, 11:26:16 PM] Loaded config.json with 2 accessories and 5 platforms.
[7/23/2021, 11:26:16 PM] Loaded 6 cached accessories from cachedAccessories.
[7/23/2021, 11:26:16 PM] ---
[7/23/2021, 11:26:17 PM] Loaded plugin: homebridge-config-ui-x@4.41.1
[7/23/2021, 11:26:17 PM] Registering platform 'homebridge-config-ui-x.config'
[7/23/2021, 11:26:17 PM] ---
[7/23/2021, 11:26:17 PM] Loaded plugin: homebridge-fritz-platform@6.0.14
[7/23/2021, 11:26:18 PM] Registering platform 'homebridge-fritz-platform.FritzPlatform'
[7/23/2021, 11:26:18 PM] ---
[7/23/2021, 11:26:18 PM] Loaded plugin: homebridge-raspberrypi-temperature@0.0.8
[7/23/2021, 11:26:18 PM] Registering accessory 'homebridge-raspberrypi-temperature.RaspberryPiTemperature'
[7/23/2021, 11:26:18 PM] ---
[7/23/2021, 11:26:18 PM] Loaded plugin: homebridge-rpi-controller@2.1.9
[7/23/2021, 11:26:18 PM] Registering accessory 'homebridge-rpi-controller.RaspberryPi'
[7/23/2021, 11:26:18 PM] ---
[7/23/2021, 11:26:18 PM] Loaded plugin: homebridge-samsung-tizen@5.0.1
[7/23/2021, 11:26:18 PM] Registering platform 'homebridge-samsung-tizen.SamsungTizen'
[7/23/2021, 11:26:18 PM] ---
[7/23/2021, 11:26:19 PM] Loaded plugin: homebridge-xbox-tv@1.5.38
[7/23/2021, 11:26:19 PM] Registering platform 'homebridge-xbox-tv.XboxTv'
[7/23/2021, 11:26:19 PM] ---
[7/23/2021, 11:26:19 PM] Loaded plugin: homebridge-skyq-tvremote@1.4.0-beta.2
[7/23/2021, 11:26:19 PM] Registering platform 'homebridge-skyq-tvremote.skyq-tvremote'
[7/23/2021, 11:26:19 PM] ---
[7/23/2021, 11:26:19 PM] Loading 5 platforms...
[7/23/2021, 11:26:19 PM] [Config] Initializing config platform...
[7/23/2021, 11:26:19 PM] [Config] Running in Service Mode
[7/23/2021, 11:26:19 PM] [SamsungTizen] Initializing SamsungTizen platform...
[7/23/2021, 11:26:19 PM] [XboxTv] Initializing XboxTv platform...
[7/23/2021, 11:26:19 PM] [FritzPlatform] Initializing FritzPlatform platform...
[7/23/2021, 11:26:21 PM] [skyq-tvremote] Initializing skyq-tvremote platform...
[7/23/2021, 11:26:21 PM] [skyq-tvremote] Sky TV platform finished initializing!
[7/23/2021, 11:26:21 PM] Loading 2 accessories...
[7/23/2021, 11:26:21 PM] [RaspberryPi CPU Temperature] Initializing RaspberryPiTemperature accessory...
[7/23/2021, 11:26:21 PM] [RaspberryPi CPU Temperature] update currentTemperatureCharacteristic value: 42.355
[7/23/2021, 11:26:21 PM] [Raspberry Pi] Initializing RaspberryPi accessory...
[7/23/2021, 11:26:21 PM] [XboxTv] didFinishLaunching
[7/23/2021, 11:26:21 PM] [XboxTv] Adding new accessory: Xbox One X
[7/23/2021, 11:26:21 PM] [XboxTv] prepareAccessory
[7/23/2021, 11:26:21 PM] [XboxTv] prepareInformationService
Preparing Advertiser for 'Homebridge 8782 486A' using ciao backend!
Setup Payload:
X-HM://0024OHSBT1AKJ
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 731-67-273 │     
    └────────────┘     
                       
Starting to advertise 'Homebridge 8782 486A' using ciao backend!
[7/23/2021, 11:26:21 PM] Homebridge v1.3.4 (Homebridge 8782) is running on port 51979.
[7/23/2021, 11:26:21 PM] [skyq-tvremote] RequestError: Error: connect ECONNREFUSED 192.168.178.48:9006
    at new RequestError (/usr/local/lib/node_modules/homebridge-skyq-tvremote/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/usr/local/lib/node_modules/homebridge-skyq-tvremote/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/usr/local/lib/node_modules/homebridge-skyq-tvremote/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/usr/local/lib/node_modules/homebridge-skyq-tvremote/node_modules/request/request.js:185:22)
    at Request.emit (events.js:375:28)
    at Request.onRequestError (/usr/local/lib/node_modules/homebridge-skyq-tvremote/node_modules/request/request.js:877:8)
    at ClientRequest.emit (events.js:375:28)
    at Socket.socketErrorListener (_http_client.js:475:9)
    at Socket.emit (events.js:375:28)
    at emitErrorNT (internal/streams/destroy.js:106:8) {
  cause: Error: connect ECONNREFUSED 192.168.178.48:9006
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1148:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '192.168.178.48',
    port: 9006
  },
  error: Error: connect ECONNREFUSED 192.168.178.48:9006
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1148:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '192.168.178.48',
    port: 9006
  },
  options: {
    url: 'http://192.168.178.48:9006/as/system/information',
    json: true,
    callback: [Function: RP$callback],
    transform: undefined,
    simple: true,
    resolveWithFullResponse: false,
    transform2xxOnly: false
  },
  response: undefined
}
[7/23/2021, 11:26:21 PM] [skyq-tvremote] [SkyQMini] Perhaps the IP address is incorrect
[7/23/2021, 11:26:21 PM] [FritzPlatform] FRITZ!Box 6660 Cable Master: Configuring cached accessory...
[7/23/2021, 11:26:21 PM] [FritzPlatform] FRITZ!Box 6660 Cable Master Wifi 2ghz: Configuring cached accessory...
[7/23/2021, 11:26:21 PM] [FritzPlatform] FRITZ!Box 6660 Cable Master Wifi 5ghz: Configuring cached accessory...
[7/23/2021, 11:26:21 PM] [FritzPlatform] FRITZ!Box 6660 Cable Master Wifi guest: Configuring cached accessory...
[7/23/2021, 11:26:21 PM] [FritzPlatform] FRITZ!Box 6660 Cable: Configuring cached accessory...
[7/23/2021, 11:26:21 PM] [FritzPlatform] FRITZ!Repeater 2400: Configuring cached accessory...
[7/23/2021, 11:26:21 PM] [FritzPlatform] FRITZ!Box 6660 Cable Master: Setup accessory...
[7/23/2021, 11:26:21 PM] [FritzPlatform] FRITZ!Box 6660 Cable Master Wifi 2ghz: Setup accessory...
[7/23/2021, 11:26:21 PM] [FritzPlatform] FRITZ!Box 6660 Cable Master Wifi 5ghz: Setup accessory...
[7/23/2021, 11:26:21 PM] [FritzPlatform] FRITZ!Box 6660 Cable Master Wifi guest: Setup accessory...
[7/23/2021, 11:26:21 PM] [FritzPlatform] FRITZ!Box 6660 Cable: Setup accessory...
[7/23/2021, 11:26:21 PM] [FritzPlatform] FRITZ!Repeater 2400: Setup accessory...
Preparing Advertiser for 'Wohnzimmer Fernseher 1DF4' using ciao backend!
Preparing Advertiser for 'Schlafzimmer Fernseher 5424' using ciao backend!
Starting to advertise 'Wohnzimmer Fernseher 1DF4' using ciao backend!
[7/23/2021, 11:26:21 PM] Wohnzimmer Fernseher 1DF4 is running on port 37925.
[7/23/2021, 11:26:21 PM] Please add [Wohnzimmer Fernseher 1DF4] manually in Home app. Setup Code: 731-67-273
Starting to advertise 'Schlafzimmer Fernseher 5424' using ciao backend!
[7/23/2021, 11:26:21 PM] Schlafzimmer Fernseher 5424 is running on port 33741.
[7/23/2021, 11:26:21 PM] Please add [Schlafzimmer Fernseher 5424] manually in Home app. Setup Code: 731-67-273
Preparing Advertiser for 'SkyQ B08F' using ciao backend!
Starting to advertise 'SkyQ B08F' using ciao backend!
[7/23/2021, 11:26:21 PM] SkyQ B08F is running on port 38637.
[7/23/2021, 11:26:21 PM] Please add [SkyQ B08F] manually in Home app. Setup Code: 731-67-273
[7/23/2021, 11:26:21 PM] [XboxTv] Device: 192.168.178.46 Xbox One X, debug devInfo: {
  manufacturer: 'Microsoft Corporation',
  modelName: 'Model Name',
  serialNumber: 'FD00708521C3B595',
  firmwareRevision: '10.0.22000'
}
[7/23/2021, 11:26:21 PM] [XboxTv] prepareTelevisionService
[7/23/2021, 11:26:21 PM] [XboxTv] prepareSpeakerService
[7/23/2021, 11:26:21 PM] [XboxTv] prepareInputsService
[7/23/2021, 11:26:21 PM] [XboxTv] Device: 192.168.178.46 Xbox One X, read saved Apps name: {}
[7/23/2021, 11:26:21 PM] [XboxTv] Device: 192.168.178.46 Xbox One X, read target  state successful: {}
[7/23/2021, 11:26:21 PM] [XboxTv] prepareInputsButtonService
[7/23/2021, 11:26:21 PM] [XboxTv] Device: 192.168.178.46 Xbox One X, publishExternalAccessories.
Preparing Advertiser for 'Xbox One X 9044' using ciao backend!
Starting to advertise 'Xbox One X 9044' using ciao backend!
[7/23/2021, 11:26:21 PM] Xbox One X 9044 is running on port 35153.
[7/23/2021, 11:26:21 PM] Please add [Xbox One X 9044] manually in Home app. Setup Code: 731-67-273
[7/23/2021, 11:26:22 PM] [RaspberryPi CPU Temperature] update currentTemperatureCharacteristic value: 41.381
[7/23/2021, 11:26:22 PM] [RaspberryPi CPU Temperature] update currentTemperatureCharacteristic value: 42.355
[7/23/2021, 11:26:23 PM] [RaspberryPi CPU Temperature] update currentTemperatureCharacteristic value: 42.842
[7/23/2021, 11:26:24 PM] [RaspberryPi CPU Temperature] update currentTemperatureCharacteristic value: 42.842
[7/23/2021, 11:26:25 PM] [RaspberryPi CPU Temperature] update currentTemperatureCharacteristic value: 43.329
[7/23/2021, 11:26:25 PM] [skyq-tvremote] [SkyQ] Get Active: ACTIVE
[7/23/2021, 11:26:26 PM] [RaspberryPi CPU Temperature] update currentTemperatureCharacteristic value: 42.355
[7/23/2021, 11:26:26 PM] [XboxTv] Device: 192.168.178.46 Xbox One X, App: Spotify, target visibility state: SHOWN
[7/23/2021, 11:26:27 PM] [RaspberryPi CPU Temperature] update currentTemperatureCharacteristic value: 42.842
[7/23/2021, 11:26:28 PM] [RaspberryPi CPU Temperature] update currentTemperatureCharacteristic value: 41.868
[7/23/2021, 11:26:28 PM] [XboxTv] Device: 192.168.178.46 Xbox One X, discovered.
[7/23/2021, 11:26:29 PM] [RaspberryPi CPU Temperature] update currentTemperatureCharacteristic value: 41.381
[7/23/2021, 11:26:29 PM] [Wohnzimmer Fernseher] [DEBUG] {
  method: 'ms.channel.emit',
  params: { data: '', to: 'host', event: 'ed.installedApp.get' }
}
[7/23/2021, 11:26:29 PM] [Wohnzimmer Fernseher] [DEBUG] {
  data: { clients: [ [Object] ], id: 'c84310c5-1356-40f1-84be-f4a92e28ad33' },
  event: 'ms.channel.connect'
}
[7/23/2021, 11:26:29 PM] [Schlafzimmer Fernseher] TV is offline! Can't get installed apps!
[7/23/2021, 11:26:29 PM] [Schlafzimmer Fernseher] [DEBUG] TvOfflineError: TV is offline! Can't get installed apps!
    at WebSocketSecure.getApplications (/usr/lib/node_modules/homebridge-samsung-tizen/lib/methods/ws.js:55:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
[7/23/2021, 11:26:29 PM] [Wohnzimmer Fernseher] [DEBUG] {
  data: {
    data: [
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object]
    ]
  },
  event: 'ed.installedApp.get',
  from: 'host'
}
[7/23/2021, 11:26:30 PM] [RaspberryPi CPU Temperature] update currentTemperatureCharacteristic value: 41.381
[7/23/2021, 11:26:30 PM] [XboxTv] Device: 192.168.178.46 Xbox One X, connection error: {
  error: 'device_unavailable',
  message: 'Xbox is unavalable on 192.168.178.46'
}
↪ Device: Wohnzimmer Fernseher
-----------------------------------
App Name :  Netflix
App ID   :  11101200001
-----------------------------------
App Name :  Apple TV
App ID   :  3201807016597
-----------------------------------
App Name :  Apple Music
App ID   :  3201908019041
-----------------------------------
App Name :  Disney+
App ID   :  3201901017640
-----------------------------------
App Name :  Universal Guide
App ID   :  3201710015067
-----------------------------------
App Name :  Prime Video
App ID   :  3201512006785
-----------------------------------
App Name :  e-Manual
App ID   :  20192100002
-----------------------------------
App Name :  YouTube
App ID   :  111299001912
-----------------------------------
App Name :  Rakuten TV
App ID   :  3201511006428
-----------------------------------
App Name :  DAZN
App ID   :  3201607009920
-----------------------------------
App Name :  ZDF mediathek
App ID   :  3201705012365
-----------------------------------
App Name :  ARD Mediathek
App ID   :  3201412000679
-----------------------------------
App Name :  Internet
App ID   :  org.tizen.browser
-----------------------------------
App Name :  Joyn
App ID   :  3201502001386
-----------------------------------
App Name :  maxdome
App ID   :  3201803015887
-----------------------------------
App Name :  Gallery
App ID   :  3201710015037
-----------------------------------
App Name :  Samsung SportWorld
App ID   :  3201903018105
-----------------------------------
App Name :  PrivacyChoices
App ID   :  3201909019271
-----------------------------------
App Name :  Samsung Promotion
App ID   :  3201807016658
-----------------------------------
App Name :  waipu.tv – Fernsehen wie noch nie
App ID   :  3201804016033
-----------------------------------
App Name :  MagentaTV
App ID   :  3201907018746
-----------------------------------
App Name :  TikTok
App ID   :  3202008021577
-----------------------------------
App Name :  Sky Ticket
App ID   :  3201411000562
-----------------------------------
App Name :  ARTE
App ID   :  3202011022316
-----------------------------------
App Name :  CUPRA
App ID   :  3201909019084
-----------------------------------
App Name :  Audi
App ID   :  11111358501
-----------------------------------
App Name :  TVNOW PREMIUM
App ID   :  3201908018988
-----------------------------------
[7/23/2021, 11:26:31 PM] [RaspberryPi CPU Temperature] update currentTemperatureCharacteristic value: 41.381
[7/23/2021, 11:26:31 PM] [skyq-tvremote] [SkyQ] Update Active: ACTIVE
[7/23/2021, 11:26:32 PM] [RaspberryPi CPU Temperature] update currentTemperatureCharacteristic value: 40.407
[7/23/2021, 11:26:33 PM] [RaspberryPi CPU Temperature] update currentTemperatureCharacteristic value: 40.894
[7/23/2021, 11:26:33 PM] [XboxTv] Device: 192.168.178.46 Xbox One X, discovered.
[7/23/2021, 11:26:34 PM] [RaspberryPi CPU Temperature] update currentTemperatureCharacteristic value: 40.407
[7/23/2021, 11:26:35 PM] [RaspberryPi CPU Temperature] update currentTemperatureCharacteristic value: 40.407
[7/23/2021, 11:26:35 PM] [XboxTv] Device: 192.168.178.46 Xbox One X, connection error: {
  error: 'device_unavailable',
  message: 'Xbox is unavalable on 192.168.178.46'
}
[7/23/2021, 11:26:36 PM] [RaspberryPi CPU Temperature] update currentTemperatureCharacteristic value: 40.407
[7/23/2021, 11:26:37 PM] [RaspberryPi CPU Temperature] update currentTemperatureCharacteristic value: 40.894
[7/23/2021, 11:26:38 PM] [RaspberryPi CPU Temperature] update currentTemperatureCharacteristic value: 39.92
[7/23/2021, 11:26:38 PM] [XboxTv] Device: 192.168.178.46 Xbox One X, discovered.
[7/23/2021, 11:26:39 PM] [RaspberryPi CPU Temperature] update currentTemperatureCharacteristic value: 39.92
[7/23/2021, 11:26:40 PM] [RaspberryPi CPU Temperature] update currentTemperatureCharacteristic value: 40.407
[7/23/2021, 11:26:40 PM] [XboxTv] Device: 192.168.178.46 Xbox One X, connection error: {
  error: 'device_unavailable',
  message: 'Xbox is unavalable on 192.168.178.46'
```

**Comment by EpicKris** [comment]
Are you sure that the IP address is correct?

Could you try to visit http://192.168.178.48:9006/as/system/information from a browser on your local network and see if that shows anything?
