### ISSUE TITLE
RequestError: Error: connect ECONNREFUSED 

### ISSUE THREAD

**Issue by neiloakley** [neilpatel121/homebridge-skyq-tvremote#41]
**Describe The Bug:**
Devices show as 'No Response' in Home app. Child bridge constantly restarts in a error/restart loop. 

**To Reproduce:**
Unknown. No variables have changes on my setup. Perhaps this relates to a Sky Q firmware update?

**Expected behavior:**
Child bridge should not continually loop, and status should be correctly reporting in the Home app. 

**Logs:**

[03/12/2022, 20:53:02] [homebridge-skyq-tvremote] Child bridge process ended
[03/12/2022, 20:53:02] [homebridge-skyq-tvremote] Process Ended. Code: 1, Signal: null
[03/12/2022, 20:53:09] [homebridge-skyq-tvremote] Restarting Process...
[03/12/2022, 20:53:10] [homebridge-skyq-tvremote] Launched child bridge with PID 32286
[03/12/2022, 20:53:11] Registering platform 'homebridge-skyq-tvremote.skyq-tvremote'
[03/12/2022, 20:53:11] [homebridge-skyq-tvremote] Loaded homebridge-skyq-tvremote v1.4.1 child bridge successfully
[03/12/2022, 20:53:11] Loaded 0 cached accessories from cachedAccessories.0E9C43B3DB6B.
[03/12/2022, 20:53:11] [homebridge-skyq-tvremote] Sky TV platform finished initializing!
[03/12/2022, 20:53:11] Homebridge v1.5.1 (HAP v0.10.4) (homebridge-skyq-tvremote) is running on port 33299.
[03/12/2022, 20:53:11] Sky Q Living Room A6E8 is running on port 36875.
[03/12/2022, 20:53:11] Please add [Sky Q Living Room A6E8] manually in Home app. Setup Code: 343-95-717
[03/12/2022, 20:53:11] Sky Q Bedroom ABE8 is running on port 37279.
[03/12/2022, 20:53:11] Please add [Sky Q Bedroom ABE8] manually in Home app. Setup Code: 343-95-717
[03/12/2022, 20:53:11] Sky Q Extension B3E1 is running on port 39467.
[03/12/2022, 20:53:11] Please add [Sky Q Extension B3E1] manually in Home app. Setup Code: 343-95-717

/var/lib/homebridge/node_modules/homebridge-skyq-tvremote/node_modules/request-promise-core/lib/errors.js:14
        Error.captureStackTrace(this);
              ^
RequestError: Error: connect ECONNREFUSED 192.168.5.38:9006
    at new RequestError (/var/lib/homebridge/node_modules/homebridge-skyq-tvremote/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/var/lib/homebridge/node_modules/homebridge-skyq-tvremote/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/var/lib/homebridge/node_modules/homebridge-skyq-tvremote/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/var/lib/homebridge/node_modules/homebridge-skyq-tvremote/node_modules/request/request.js:185:22)
    at Request.emit (node:events:513:28)
    at Request.onRequestError (/var/lib/homebridge/node_modules/homebridge-skyq-tvremote/node_modules/request/request.js:877:8)
    at ClientRequest.emit (node:events:513:28)
    at Socket.socketErrorListener (node:_http_client:494:9)
    at Socket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
[03/12/2022, 20:53:11] [homebridge-skyq-tvremote] Child bridge process ended
[03/12/2022, 20:53:11] [homebridge-skyq-tvremote] Process Ended. Code: 1, Signal: null

**Plugin Config:**

{
    "devices": [
        {
            "name": "Sky Q Living Room",
            "ipAddress": "192.168.5.49"
        },
        {
            "name": "Sky Q Bedroom",
            "ipAddress": "192.168.5.63"
        },
        {
            "name": "Sky Q Extension",
            "ipAddress": "192.168.5.38"
        }
    ],
    "_bridge": {
        "username": "XX:XX:XX:XX:XX:XX",
        "port": 33299
    },
    "platform": "skyq-tvremote"
}

**Screenshots:**

**Environment:**

* **Plugin Version**:

V1.4.1

* **Homebridge Version**: <V1.5.1->
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**: <Raspbian>

**Comment by SmolSoftBoi** [comment]
Looks like your `Sky Q Extension` might not be on or connected to your network, could you check this please?
